models/Events.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use app\components\ActiveRecordLogger;
use yii\behaviors\BlameableBehavior;

/**
 * This is the model class for table "events".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $cost
 * @property int|null $cpd_points
 * @property string|null $start_time
 * @property string|null $end_time
 * @property string|null $start_date
 * @property string|null $end_date
 * @property string|null $description
 * @property string|null $updated_at
 * @property string|null $created_at
 * @property int|null $updated_by
 * @property int|null $created_by
 * @property string|null $venue
 */
class Events extends \yii\db\ActiveRecord
{
    public $banner;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'events';
    }

    public function behaviors()
    {
        return [
            ['class'=>ActiveRecordLogger::className()],
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => new Expression('NOW()'),
            ],
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cpd_points', 'updated_by', 'created_by','cost','members_cost' ], 'integer'],
            [['start_date', 'end_date', 'updated_at', 'created_at'], 'safe'],
            [['description'], 'string'],
            [['banner'],'file', 'skipOnEmpty'=>true, 'extensions' => 'png, jpg, jpeg', 
            'maxSize'=>1024*1024, 'mimeTypes'=> 'image/jpeg, image/png',
            ],            
            [['name', 'start_time', 'end_time', 'venue','file','is_notified'], 'string', 'max' => 100],
            [['start_date', 'end_date', 'name', 'cost', 'start_time', 'end_time', 'venue','members_cost'], 'required'],
        ];
    }

    // public function afterSave($insert, $changedAttributes)
    // {
    //     if($insert){
    //         $users = Users::find()->where(['role'=>'Member'])->all();
    //         foreach($users as $user){
    //             \Yii::$app->mailer->compose(
    //                 ['html' => 'event-html'],
    //                 [
    //                     'user' => $user,
    //                 ]
    //             )
    //             ->setFrom([\Yii::$app->params['adminEmail'] => 'ICTAU'])
    //             ->setTo($user->email)
    //             ->setSubject('New ICTAU Event')
    //             ->send();
    //         }
    //     }
    //     parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    // }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'cost' => 'Guest Cost',
            'cpd_points' => 'Cpd Points',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'start_date' => 'Start Date',
            'end_date' => 'End Date',
            'description' => 'Description',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
            'updated_by' => 'Updated By',
            'created_by' => 'Created By',
            'venue' => 'Venue',
        ];
    }

    public function getPayment(){
        return EventPayments::findOne(['event_id' => $this->id,'user_id'=>\Yii::$app->user->id]);
    }

}

controllers/EventsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Events;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EventsController implements the CRUD actions for Events model.
 */
class EventsController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Events models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Events::find()->orderBy(['start_date' => SORT_DESC]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Events model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $payment = new \app\models\GuestPayments;
        if ($payment->load(Yii::$app->request->post())) {
            if($payment->amount <= 0){
                $payment->status = 'Free';
                $payment->save();
                Yii::$app->session->setFlash('success','Please check your email to download the ticket!');
                return $this->redirect(['index']);
            }else{
                $payment->status = 'Pending';
                return $this->redirect(['olycash', 'event_id' => $model->id,'payment_id' => $payment->id,]);
            }
        }

        return $this->render('view', [
            'model' => $model,
            'payment' => $payment
        ]);
    }

    public function actionOlycash($event_id, $payment_id)
    {
        $event = \app\models\Events::findOne($event_id);
        $payment =  \app\models\GuestPayments::findOne($payment_id);

        return $this->render('olycash', [
            'event' => $event,
            'payment' => $payment,
        ]);
    }

    public function actionConfirm($id){
        $payment =  \app\models\GuestPayments::findOne($id);
        $purchase_id = $_POST['purchase_id'];
        $message = $_POST['message'];
        $payment_type = $_POST['payment_type'];
        if($message == 'success'){
            try {
                $payment->reference_number = $purchase_id;
                $payment->payment_type ='Olycash';
                $payment->status = 'Paid';
                if($payment->save()){
                    Yii::$app->session->setFlash('success','Please check your email to download the ticket!');
                    return $this->redirect(['/events/index']);
                }else{
                    print_r($payment->getFirstErrors());
                }
            } catch (IntegrityException $e) {
                echo $e->getMessage();
            } catch (NotFoundHttpException $e) {
                echo $e->getMessage();
            }
            return $this->redirect(['/events/index']);
        }

    }

    /**
     * Creates a new Events model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Events();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Events model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Events model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Events model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Events the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Events::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/events/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Events */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="events-form">
<div class="card-body-inner">
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cost')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'members_cost')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cpd_points')->textInput() ?>

    <?= $form->field($model, 'start_time')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'end_time')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'start_date')->textInput() ?>

    <?= $form->field($model, 'end_date')->textInput() ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'updated_at')->textInput() ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'updated_by')->textInput() ?>

    <?= $form->field($model, 'created_by')->textInput() ?>

    <?= $form->field($model, 'venue')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'file')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>
</div>

views/events/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Events */

$this->title = 'Create Events';
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="events-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/events/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Events';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="events-index">

    <div class="row pt-5 g-5">
                    <div class="offset-md-2 col-md-8">
                        <div class="row gap-3">
                            <div class="card">
                                <div class="card-header bg-white">
                                    <h4 class="mb-0">Events</h4>
                                </div>
                                <div class="card-body">
                                <?php if (Yii::$app->session->hasFlash('success')): ?>
                                    <div class="alert alert-success alert-dismissable">
                                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                        <?= Yii::$app->session->getFlash('success') ?>
                                    </div>
                                <?php endif; ?>
                                    <div class="d-grid gap-3">
                                        <?php foreach($dataProvider->models as $item ): ?>
                                        <div class="pb-2 border-bottom">
                                            <h5><?= $item['name'] ?></h5>
                                            <p><?= $item['description'] ?></p>
                                            <div class="d-flex justify-content-between align-items-center">
                                                <?= Html::a( 'Details', ['/events/view','id' =>$item['id']], ['class' => 'text-danger']) ?>
                                                <time class="h6 mb-0"><?=  date("F jS, Y", strtotime($item['start_date'])) ?></time>
                                            </div>
                                        </div>
                                        <img src="<?= Yii::getAlias('@web');?>/events/<?= $item['file']?>" width="300px" class="img-responsive" />
                                        <?php endforeach; ?>
                                  
                                   
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

   


</div>

views/events/olycash.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Payments */

$this->title = 'Oly Cash';
$this->params['breadcrumbs'][] = ['label' => 'Payments', 'url' => ['event-payments/olycash','id'=>$event->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="payments-create panel">
    <div class="panel-heading">
        <h1 class="panel-title">Pay With OlyCash</h1>
    </div>
    <div class="panel-body">
        <script>(function(d, s, id) {var js, ojs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) return;js = d.createElement(s); js.id = id;js.src = "https://share.olycash.com/en-us/sdk.js";ojs.parentNode.insertBefore(js, ojs);}(document, 'script', 'olycash-js-sdk'));</script>
        <!-- OPTIONAL: You can remove and incorporate this table in your form if desired -->
        <table class="amount-entry-form" style="border-collapse: collapse !important; max-width:250px !important;"><tr>
                <td style="border:0px;font-weight:bold;font-family: Arial, sans-serif; font-size: 17px;">Amount: </td>
                <td style="border:0px;"><select id="olycash__tempcurrency_1543470912" name="olycash__tempcurrency_1543470912" class="__olycash-temp-currency-field" style="width:85px;height:40px;padding:9px 5px 8px 5px;border: 1px solid #B2B2B2; background-color: #FFFFFF;font-family: Arial, sans-serif; font-size: 17px;"><option value="" disabled>Currency</option><option value="UGX" selected>UGX</option><option value="KES">KES</option><option value="TZS">TZS</option><option value="GHS">GHS</option><option value="ARS">ARS</option><option value="AUD">AUD</option><option value="BRL">BRL</option><option value="CAD">CAD</option><option value="CHF">CHF</option><option value="CZK">CZK</option><option value="DKK">DKK</option><option value="EUR">EUR</option><option value="GBP">GBP</option><option value="HKD">HKD</option><option value="HUF">HUF</option><option value="ILS">ILS</option><option value="JPY">JPY</option><option value="MXN">MXN</option><option value="MYR">MYR</option><option value="NOK">NOK</option><option value="NZD">NZD</option><option value="PHP">PHP</option><option value="PLN">PLN</option><option value="RUB">RUB</option><option value="SEK">SEK</option><option value="SGD">SGD</option><option value="THB">THB</option><option value="TRY">TRY</option><option value="TWD">TWD</option><option value="USD">USD</option></select></td>
                <td style="border:0px;">
            <input type="text" id="olycash__temptotal_1543470912" name="olycash__temptotal_1543470912" style="width:100px;height:40px;padding:10px;border: 1px solid #B2B2B2; background-color: #FFFFFF;font-family: Arial, sans-serif; font-size: 17px;" class="__olycash-temp-amount-field" value="<?=$payment->amount;?>" readonly="readonly" placeholder="0.00" maxlength="12"></td></tr></table><!-- END OPTIONAL --><!-- Your share code -->
            
            <!-- For Dev Testing Please uncomment the line below -->
            <!-- <div class="olycash-pay debit-only olycash--window" style="width:100% !important;" data-id="133C9BD_8B35E"> -->
            <div class="olycash-pay olycash--window" style="width:100% !important;" data-ignorefrequency="Y" data-id="133C9C6_D83460"> 
            <input type="hidden" id="olycash__category" name="olycash__category" value="156"/>
            <input type="hidden" id="olycash__total" name="olycash__total" value="<?=$event->members_cost;?>"/>
            <input type="hidden" id="olycash__currency" name="olycash__currency" value="UGX"/>
            <input type='hidden' id='olycash__post_process' name='olycash__post_process' value='olycashPostProcess'/>
            <input type='hidden' id='olycash__post_response' name='olycash__post_response' value='<?= \yii\helpers\Url::to(['confirm','id'=>$payment->id],true);?>'/>
            <input type='hidden' id='olycash__buyer_name' name='hidden' value="<?= $payment->name ?>"/>
            <input type='hidden' id='olycash__third_party_fee_paid_by' name='olycash__third_party_fee_paid_by' value="payer"/>        
        </div> 
        </div>
    </div>

</div>


<script>
    (function() {
        var callbackUrl = '<?= \yii\helpers\Url::to(['confirm','id'=>$payment->id],true); ?>';
    console.log(callbackUrl)

})();



    function olycashPostProcess(data){
        console.log(data);
        notifyPaymentCompletion(data);
    }

    function notifyPaymentCompletion(data) {
        jQuery.post('<?= \yii\helpers\Url::to(['confirm','id'=>$payment->id],true);?>', {'purchase_id': data.purchase_id, 'message': data.message, 'payment_type': data.payment_type}, function(response){
            console.log('Achest API notified. Response from API: '+JSON.stringify(response));
        });
    }

</script>

views/events/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Events */

$this->title = 'Update Events: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="events-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/events/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\Events */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Events', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="events-view">

    <!-- <p>
        <!?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <!?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p> -->
<div class="row">
    <div class="col-md-8">
    <h1 class="mt-3 mb-3"><?= Html::encode($this->title) ?></h1>
                            <div class="card">
                                <!-- <div class="card-header pt-3 d-flex flex-wrap justify-content-start bg-white">
                                    <div class="py-2 px-3 me-2 bg-dark text-white rounded">
                                        <h6 class="border-bottom pb-2">Fee - Guest</h6>
                                        <span class="d-block"><?php if(!empty($model->cost)){  echo number_format($model->cost); } else{ echo '0'; } ?> UGX</span>
                                    </div>
                                    <div class="py-2 px-3 me-2 bg-success text-white rounded">
                                        <h6 class="border-bottom pb-2">Fee - Member</h6>
                                        <span class="d-block"><?php if(!empty($model->members_cost)){ echo  number_format($model->members_cost); } else{ echo '0';} ?> UGX</span>
                                    </div>
                                    <div class="py-2 px-3 me-2 bg-danger text-white rounded">
                                        <h6 class="border-bottom pb-2">Date</h6>
                                        <span class="d-block"><?=  date("F jS, Y", strtotime($model->start_date)) ?></span>
                                    </div>
                                    <div class="py-2 px-3 me-2 bg-dark text-white rounded">
                                        <h6 class="border-bottom pb-2">Time</h6>
                                        <span class="d-block"><?=  $model->start_time.' - '.$model->end_time ?></span>
                                    </div>
                                    <div class="py-2 px-3 me-2 bg-danger text-white rounded">
                                        <h6 class="border-bottom pb-2">Venue</h6>
                                        <span class="d-block"><?=  $model->venue ?></span>
                                    </div>
                                    <div class="py-2 px-3 me-2 bg-success text-white rounded">
                                        <h6 class="border-bottom pb-2">CPD Points</h6>
                                        <span class="d-block"><?php echo $model->cpd_points; ?> </span>
                                    </div>
                                </div> -->
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <?= DetailView::widget([
                                                'model' => $model,
                                                'attributes' => [
                                                    'name', 'cost', 'start_time', 'end_time', 'venue','members_cost','start_date', 'end_date', 
                                                ],
                                            ]) ?>
                                        </div>
                                        <div class="col-md-6">
                                            <img src="<?= Yii::getAlias('@web');?>/events/<?= $model->file;?>" class="img-responsive" />
                                        </div>
                                    </div>
                                    <p><?=  $model->description ?></p>
                                </div>
                            </div>
    </div>
    <?php if($model->start_date >= date('Y-m-d')): ?>
    <div class="col-md-4">
        <h1>Register for Event</h1>
        <div class="event-payments-form">
        <div class="card-body-inner">
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($payment, 'name')->textInput(['maxlength' => true]) ?>

            <?= $form->field($payment, 'phone_number')->textInput(['maxlength' => true]) ?>

            <?= $form->field($payment, 'email')->textInput(['maxlength' => true]) ?>

            <?= $form->field($payment, 'event_id')->hiddenInput(['value' => $model->id])->label(false) ?>

            <?= $form->field($payment, 'amount')->hiddenInput(['value' => $model->cost])->label(false) ?>

            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
        </div>
    </div>
    <?php endif; ?>
</div>
    

</div>