models/EventPayments.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;
use app\components\ActiveRecordLogger;
use yii\behaviors\BlameableBehavior;

/**
 * This is the model class for table "event_payments".
 *
 * @property int $id
 * @property int|null $user_id
 * @property string|null $payment_type
 * @property int|null $event_id
 * @property string|null $amount
 * @property string|null $status
 * @property string|null $created_at
 * @property string|null $updated_at
 * @property int|null $created_by
 * @property int|null $updated_by
 * @property string|null $name
 * @property string|null $phone_number
 * @property string|null $reference_number
 * @property string|null $file
 */
class EventPayments extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'member_event_payments';
    }

    public function behaviors()
    {
        return [
            ['class'=>ActiveRecordLogger::className()],
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => new Expression('NOW()'),
            ],
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_by',
                'updatedByAttribute' => 'updated_by',
            ],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'event_id', 'created_by', 'updated_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['payment_type', 'amount', 'status', 'name', 'phone_number', 'reference_number', 'file','receipt'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'payment_type' => 'Payment Type',
            'event_id' => 'Event ID',
            'amount' => 'Amount',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'name' => 'Name',
            'phone_number' => 'Phone Number',
            'reference_number' => 'Reference Number',
            'file' => 'Ticket',
            'receipt' => 'Receipt',
        ];
    }
    public function getUser(){
        return $this->hasOne(Users::classname(), ['id' => 'user_id']);
    }

    public function getEvent(){
        return $this->hasOne(Events::classname(), ['id' => 'event_id']);
    }

    public function getName(){
        return $this->user->name;
    }


}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;
use app\models\ContactForm;
use yii\data\ActiveDataProvider;


class SiteController extends Controller
{
    public $layout = 'main';
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            // 'verbs' => [
            //     'class' => VerbFilter::className(),
            //     'actions' => [
            //         'logout' => ['post'],
            //     ],
            // ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionVerifyTicket($token)
    {
        $model = \app\models\EventPayments::findOne(base64_decode($token));
        if($model === null){
            throw new NotFoundHttpException('The requested Ticket does not exist.');
        }
        return $this->render('verify-ticket',[
            'model'=>$model,
        ]);
        // userId=licence->userId and category=registration
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if(!Yii::$app->user->isGuest){
            $role = Yii::$app->user->identity->role;
            if($role =='Member' || $role=='Organisation'){
                return $this->redirect(['/member/profile/dash']);
            }elseif($role =='Admin'){
                return $this->redirect(['/admin/default']);
            }elseif($role =='Super'){
                return $this->redirect(['/super/logs']);
            }
        }
        return $this->render('index');
    }


    public function actionMembershipDirectory()
    {
        $licenses = new \yii\data\ActiveDataProvider([
            'query' => \app\models\Licenses::find()->where(['>=','end_date',date('Y-m-d')]),
        ]);

        $searchModel = new \app\models\DirectorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('membership-directory',[
            'dataProvider' => $dataProvider,
            'model' => $searchModel
        ]);
    }
    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['index']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['index']);
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionRegister()
    {
        $model = new \app\models\Users;
        $model->scenario = 'create';
        if ($model->load(Yii::$app->request->post())) {
            $model->role = 'Member';
            if($model->save()){
                $notification = new \app\models\Notifications;
                $admin = \app\models\Users::findOne(['role'=>'Admin']);
                $notification->user_id = $admin->id;
                $notification->subject = 'New Account Created';
                $message = 'Account created successfully.';
                $notification->message = $message;
                $notification->save();
                \Yii::$app->mailer->compose(
                    ['html' => 'registration-html'],
                    [
                        'user' => $model,
                    ]
                )
                ->setFrom([\Yii::$app->params['adminEmail'] => 'ICTAU'])
                ->setTo($model->email)
                ->setSubject('Confirmation Email')
                ->send();

                Yii::$app->session->setFlash('success',$message);
                return $this->redirect(['/home/index']);        
            }
        }
        return $this->render('register', [
            'model' => $model,
        ]);
    }

    public function actionRegisterOrganisation()
    {
        $model = new \app\models\Users;
        $model->scenario = 'create';
        if ($model->load(Yii::$app->request->post())) {
            $model->role = 'Organisation';
            $model->first_name = '';
            $model->last_name = '';
            if($model->save()){
                $notification = new \app\models\Notifications;
                $admin = \app\models\Users::findOne(['role'=>'Admin']);
                $notification->user_id = $admin->id;
                $notification->subject = 'New Account Created';
                $message = 'Account created successfully.';
                $notification->message = $message;
                $notification->save();
                \Yii::$app->mailer->compose(
                    ['html' => 'registration-html'],
                    [
                        'user' => $model,
                    ]
                )
                ->setFrom([\Yii::$app->params['adminEmail'] => 'ICTAU'])
                ->setTo($model->email)
                ->setSubject('Confirmation Email')
                ->send();

                Yii::$app->session->setFlash('success',$message);
                return $this->redirect(['/home/index']);        
            }
        }
        return $this->render('register-organisation', [
            'model' => $model,
        ]);
    }
    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }
        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

        /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (\Exception $e) {
            Yii::$app->session->setFlash('error',$e->getMessage());
            return $this->redirect(['login']);
        }
        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved successfully.');
            return $this->goHome();
        }
        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }


}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact col-md-6 col-md-offset-3">
<div class="panel panel-info">
<div class="card-body">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-12">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>
</div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
$logopath = Yii::$app->request->baseUrl;

$this->title = 'ICTAU';
?>
<div class="site-index">

<div class="row">
<div  class="col-md-6">
    <div class="d-none d-lg-block p-0 img img-cover">
<img  src="<?php echo $logopath; ?>/images/o.jpg"/>
    </div>
</div>
<div  class="col-md-6">
login here
</div>
</div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <!-- <!?php if (Yii::$app->session->hasFlash('success')): ?>
        <div class="alert alert-success alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <!?= Yii::$app->session->getFlash('success') ?>
        </div>
    <!?php endif; ?> -->

<br><br>

<div class="col-lg-6 offset-lg-3 px-md-5 py-3 py-md-5 bg-white">

<h1 class="mb-3">Login</h1>
    <span>Create your account here</span>

        <?php $form = ActiveForm::begin([
            'id' => 'login-form',
            'layout' => 'horizontal',
            'fieldConfig' => [
                'template' => "{label}\n<div class=\"col-lg-12\">{input}</div>\n<div class=\"col-lg-12\">{error}</div>",
                'labelOptions' => ['class' => 'col-lg-1 control-label'],
            ],
        ]); ?>

        <?= $form->field($model, 'email')->textInput() ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-11\">{input} {label}</div>\n<div class=\"col-lg-12\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-6">
                <?= Html::submitButton('Login', ['class' => 'btn btn-danger', 'name' => 'login-button']) ?>
            </div>
            <div class="col-md-6">
                <?= Html::a('Forgotten Password?', ['/user/request-password-reset']);?>
            </div>
        </div>

        Have no account yet? <?= Html::a('Register Here', ['register']);?>
        Forgotten Password? <?= Html::a('R Here', ['register']);?>



    <?php ActiveForm::end(); ?>
    <br>
</div>
</div>

views/site/membership-directory.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
$logopath = Yii::$app->request->baseUrl;
use yii\widgets\LinkPager;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Membership Directory';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-index">
     <?php //print_r($dataProvider->models); ?>
    <h1><?= Html::encode($this->title) ?></h1>
    <section class="area-members site-sec">
        <div class="club-search">

            <?php $form = ActiveForm::begin([
                'action' => ['membership-directory'],
                'method' => 'get',
                'options' => ['data-pjax' => true ]
            ]); ?>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'q')->textInput(['placeholder'=>"Enter Name",'autofocus'=>false])->label(false) ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="form-group">
                        <?= Html::submitButton('Search', ['class' => 'btn btn-md btn-danger']) ?>
                    </div>
                </div>
            </div><br>
            <?php ActiveForm::end(); ?>
        </div>

        <div class="site-sec-wrap">
            <ul class="list">
                <?php foreach ($dataProvider->models as $item):?>
                <li class="list-item list-item-img-txt-below">
                    <div class="img img-cover">
                    <?php    
                        if($item->user->photo){
                            echo Html::img('@web/photos/'.$item->user->photo);
                        }else{
                            echo Html::img('@web/photos/default.png');
                        }
                    ?>
                    </div>
                    <div class="txt">
                        <span class="category"><?php echo $item->application->membership->name; ?></span>
                        <h4 class="title"><?php echo $item->user->name ; ?></h4>
                        <p class="excerpt">
                            <?php 
                                if($item->user->brief_bio){
                                    echo $item->user->brief_bio; 
                                }else{
                                    echo "Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero, labore?";
                                }
                            ?>
                        </p>
                        <?php if($item->user->website):?>
                        Website: <?= Html::a('Click Here',$item->user->website,['target'=>'_blank']); ?>
                        <?php endif; ?>
                    </div>
                </li>
                <?php endforeach; ?>

            </ul>
            
            <div class="row">
                <div class="col-md-12">
            <?php  echo LinkPager::widget([
                'pagination' => $dataProvider->pagination,
            ]) ?>
                </div>
            </div>
            
        </div>
    </section>

</div>

views/site/register-organisation.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Create Account';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
<br><br>

<div class="col-lg-6 offset-lg-3 px-md-5 py-3 py-md-5 bg-white">

    <div class="card-body">

    <h1 class="mb-3">Register Organisation</h1>
    <span>Create your account here</span>


        <?php $form = ActiveForm::begin([
            // 'id' => 'login-form',
            // // 'layout' => 'horizontal',
            // 'fieldConfig' => [
            //     'template' => "{label}\n<div class=\"col-lg-12\">{input}</div>\n<div class=\"col-lg-12\">{error}</div>",
            //     'labelOptions' => ['class' => 'col-lg-12'],
            // ],
        ]); ?>

        <div class="row">
            <div class="col-md-12">        
                <?= $form->field($model, 'organisation')->textInput(['placeholder'=>'Organisation Name','required'=>true]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'email')->textInput(['placeholder'=>'Email Address','required'=>true]) ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'primary_phone_number')->textInput(['placeholder'=>'Phone Number','required'=>true]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'password')->passwordInput(['placeholder'=>'Password','required'=>true]) ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'password_confirm')->passwordInput(['placeholder'=>'Confirm Password','required'=>true]) ?>
            </div>
        </div>        

        <div class="form-group">
            <?= Html::submitButton('Create Account', ['class' => 'btn btn-danger', 'name' => 'login-button']) ?>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?= Html::a('Register Individual','register'); ?>
            </div>
        </div>

    </div>

    <?php ActiveForm::end(); ?>
    <br>
    </div>
</div>
</div>

views/site/register.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Create Account';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
<br><br>

<div class="col-lg-6 offset-lg-3 px-md-5 py-3 py-md-5 bg-white">

    <div class="card-body">

    <h1 class="mb-3">Register</h1>
    <span>Create your account here</span>


        <?php $form = ActiveForm::begin([
            // 'id' => 'login-form',
            // // 'layout' => 'horizontal',
            // 'fieldConfig' => [
            //     'template' => "{label}\n<div class=\"col-lg-12\">{input}</div>\n<div class=\"col-lg-12\">{error}</div>",
            //     'labelOptions' => ['class' => 'col-lg-12'],
            // ],
        ]); ?>

        <div class="row">
            <div class="col-md-6">        
                <?= $form->field($model, 'first_name')->textInput(['placeholder'=>'First Name','required'=>true]) ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'last_name')->textInput(['placeholder'=>'Last Name','required'=>true]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'email')->textInput(['placeholder'=>'Email Address','required'=>true]) ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'primary_phone_number')->textInput(['placeholder'=>'Phone Number','required'=>true]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'password')->passwordInput(['placeholder'=>'Password','required'=>true]) ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'password_confirm')->passwordInput(['placeholder'=>'Confirm Password','required'=>true]) ?>
            </div>
        </div>        

        <div class="form-group">
            <?= Html::submitButton('Create Account', ['class' => 'btn btn-danger', 'name' => 'login-button']) ?>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?= Html::a('Register Organisation Here','register-organisation'); ?>
            </div>
        </div>

    </div>

    <?php ActiveForm::end(); ?>
    <br>
    </div>
</div>
</div>

views/site/requestPasswordResetToken.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/resetPassword.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

            <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/verify-ticket.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Ticket Verification';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-verify">
    <h1><?= Html::encode($this->title) ?></h1>
    <h5><b>Event Name: </b><?= $model->event->name;?></h5>
    <h5><b>Event Venue: </b><?= $model->event->venue;?></h5>
    <h5><b>Event Fee: </b><?= $model->event->cost ? $model->event->cost : $model->event->members_cost?></h5>
    <h5><b>Start Date: </b><?= $model->event->start_date;?></h5>
    <h5><b>End Date: </b><?= $model->event->end_date;?></h5>
    <h5><b>Start Time: </b><?= $model->event->start_time;?></h5>
    <h5><b>Closing Time: </b><?= $model->event->end_date;?></h5>
</div>