modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use yii\web\Controller;
use app\models\Events;
use app\models\Licenses;
use app\models\MembershipTypes;


/**
 * Default controller for the `Admin` module
 */
class DefaultController extends Controller
{
    public function beforeAction( $action )
	{
		if ( \Yii::$app->getUser()->isGuest ) {
			return \Yii::$app->getResponse()->redirect( \yii\helpers\Url::to(['/']) )->send();
		}
		return parent::beforeAction( $action ); // TODO: Change the autogenerated stub
	}
    
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        
        // Get upcoming events

        

        $time = new \DateTime('now');
        $today = $time->format('Y-m-d');
        $current_events = Events::find()->where(['>=', 'end_date', $today])->count();

        $upcoming_events = Events::find()->where(['>=', 'end_date', $today])->limit(8)->all();

        // Get Latest License

        $subqueryActive = Licenses::find()->select('max(id)')->groupBy('user_id');
        $activelicense = Licenses::find()->where(['in','id',$subqueryActive])
        ->andWhere(['>=', 'end_date', date('Y-m-d')])->count();

        $subqueryExpired = Licenses::find()->select('max(id)')->groupBy('user_id');
        $exlicense = Licenses::find()->where(['in','id',$subqueryExpired])
        ->andWhere(['<', 'end_date', date('Y-m-d')])->count();

        $types = MembershipTypes::find()->count();
        $searchModel = new \app\modules\admin\models\ApplicationsSearch();
        $dataProvider = $searchModel->search(\Yii::$app->getRequest()->queryParams);
        return $this->render('index',[
            'current_events' => $current_events,
            'types' => $types,
            'upcoming_events' => $upcoming_events,
            'activelicense' => $activelicense ? $activelicense : 0,
            'exlicense' => $exlicense ? $exlicense : 0,
            'dataProvider' => $dataProvider,
        ]);
    }
}

modules/admin/controllers/ReportsController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\ActiveDataProvider;
use app\models\Users;
use app\models\Licenses;
use app\models\Events;
use app\models\Payments;
use app\models\EventPayments;
use app\models\EventFeedback;
use app\models\GuestPayments;
use app\models\Applications;
use app\models\Notifications;
use app\modules\admin\models\UsersSearch;

class ReportsController extends Controller
{
    // public $layout = '/dashboard/main.php';
    /**
     * {@inheritdoc}
     */
    

    /**
     * Displays homepage.
     *
     * @return string
     */
    // public function actionIndex()
    // {
    //     $model = new LoginForm();

    //     return $this->render('index', [
    //         'model' => $model,
    //     ]);
    // }

    public function actionIndividualMembership()
    {
        $query = Users::find()->where(['role'=>'Member'])
        ->joinWith('licences.application.memberhip')
        ->andWhere(['like','membership_types.name','Individual']);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);

        return $this->render('individual-membership', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCorporateMembership()
    {
        $query = Users::find()->where(['role'=>'Organisation'])
        ->joinWith('licences.application.memberhip')
        ->andWhere(['like','membership_types.name','%corporate%',false])
        ->orWhere(['like','membership_types.name','%government%',false]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);

        return $this->render('corporate-membership', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionStudentMembership()
    {
        $query = Users::find()->where(['role'=>'Member'])
        ->joinWith('licences.application.memberhip')
        ->andWhere(['like','membership_types.name','Student']);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);

        return $this->render('student-membership', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionRegisteredMembers()
    {
        $query = Users::find()->where(['role'=>'Member'])
        ->joinWith('licences.application.memberhip');
        // ->andWhere(['like','membership_types.name','Corporate']);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);

        return $this->render('registered-members', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionActiveMembers()
    {
        $query = Users::find()->where(['role'=>'Member'])
        ->joinWith('licences')
        ->andWhere(['>=','licenses.end_date',date('Y-m-d')]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);

        return $this->render('active-members', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionMembershipReports($from_date=null, $to_date=null,$type_id=null)
    {
        $from_date = $from_date ? $from_date : date('2021-01-01');
        $to_date = $to_date ? $to_date : date('Y-12-31');

        if(!$type_id){
            $query = Users::find();
        }else{
            $query = Users::find()
            ->joinWith('licences.application.memberhip')
            ->andWhere(['>=','licenses.created_at',$from_date])
            ->andWhere(['<=','licenses.created_at',$to_date])
            ->andWhere(['membership_types.id'=>$type_id]);    
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);
        // var_dump($dataProvider);
        // die();

        return $this->render('membership-report', [
            'dataProvider' => $dataProvider,
            'from_date' => $from_date,
            'to_date' => $to_date,
            'type_id' => $type_id,
        ]);
    }

        /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionMembershipReport()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionCorporateReport()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->csearch(Yii::$app->request->queryParams);

        return $this->render('indexc', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }



    public function actionInactiveMembers()
    {
        $query = Users::find()->where(['role'=>'Member'])
        ->joinWith('licences')
        ->andWhere(['<','licenses.end_date',date('Y-m-d')]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);

        return $this->render('inactive-members', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionUpcomingEvents()
    {
        $query = Events::find()->where(['>=','end_date',date('Y-m-d')]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);

        return $this->render('upcoming-events', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionPastEvents()
    {
        $query = Events::find()->where(['<','end_date',date('Y-m-d')]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);

        return $this->render('past-events', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionMembershipPayments()
    {
        $query = Payments::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);

        return $this->render('membership-payments', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionEventPaymentsMembers()
    {
        $query = EventPayments::find()->where(['>','amount',0]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);

        return $this->render('event-payments-members', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionEventPaymentsGuests()
    {
        $query = GuestPayments::find();

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false,
        ]);

        return $this->render('event-payments-guests', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionDelete($id)
    {
        Licenses::deleteAll(['user_id'=>$id]);
        EventPayments::deleteAll(['user_id'=>$id]);
        Payments::deleteAll(['user_id'=>$id]);
        Applications::deleteAll(['user_id'=>$id]);
        Notifications::deleteAll(['user_id'=>$id]);
        EventFeedback::deleteAll(['user_id'=>$id]);
        Users::findOne($id)->delete();
        
        return $this->redirect(['/admin/reports/membership-report']);
    }


 
}

modules/admin/views/default/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = '404 - Not Found Error';
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

modules/admin/views/default/index.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $user app\models\Applications */

$this->title = 'Dashboard';
$notifications = \app\models\Notifications::find()->where(['user_id'=>\Yii::$app->user->id])->orderBy('id desc')->limit(3)->all();

?>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-warning card-header-icon">
            <div class="card-icon">
              <i class="material-icons">content_copy</i>
            </div>
            <p class="card-category">Active Members</p>
            <h3 class="card-title"><?= $activelicense; ?></h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">library_books</i>
              <a href="<?=\yii\helpers\Url::to(['reports/active-members']);?>">View Active Members</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="material-icons">store</i>
            </div>
            <p class="card-category">Inactive Members</p>
            <h3 class="card-title"><?= $exlicense ?></h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">date_range</i> 
              <a href="<?=\yii\helpers\Url::to(['reports/inactive-members']);?>">View Inactive Members</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-danger card-header-icon">
            <div class="card-icon">
              <i class="material-icons">info_outline</i>
            </div>
            <p class="card-category">Upcoming Events</p>
            <h3 class="card-title"><?= $current_events ?></h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">local_offer</i> 
              <a href="<?=\yii\helpers\Url::to(['reports/upcoming-events']);?>">View Upcoming Events</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-info card-header-icon">
            <div class="card-icon">
              <i class="fa fa-twitter"></i>
            </div>
            <p class="card-category">Membership Tiers</p>
            <h3 class="card-title"><?= $types ?></h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">update</i> 
              <a href="<?=\yii\helpers\Url::to(['/admin/membership-types']);?>">Membership Tiers</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header card-header-danger card-header-icon">
            <!-- <div class="card-icon">
              <i class="material-icons">account_box</i>
            </div> -->
            <h4 class="card-title">
                Recent Applications
            </h4>
          </div>
          <div class="card-body">
            <div class="material-datatables">
                <?php Pjax::begin([
                    'enablePushState'=>true,
                ]); ?>
                <?= GridView::widget([
                    'id' => 'users',
                    'tableOptions' => [
                        'class' => 'table table-striped table-no-bordered table-hover',
                    ],
                    'options' => ['class' => 'table-responsive grid-view'],
                    'dataProvider' => $dataProvider,
                    'columns' => [
                        [
                            'label' => 'Member Name',
                            'attribute' => 'user_id',
                            'value' => function($data){
                                return $data->user->name;
                            },
                        ],
                        [
                            'attribute' =>'status',
                            'filter'    => [ "On Hold"=>"On Hold", "Pending Approval"=>"Pending Approval", "Review"=>"Review", "Complete"=>"Complete", "Rejected"=>"Rejected" ],
                            'label' => 'Status',
                            'value' => function($data){
                              $labels = ['On Hold'=>'primary','Paid'=>'primary','Pending Approval'=>'warning','Pending License'=>'warning','Pending Payment'=>'info','Review'=>'default','Complete'=>'success','Rejected'=>'danger',];
                              return '<span style="padding:5px" class="alert alert-'.$labels[$data->status].'">'.$data->status.'</span>';
                            },
                            'format'=>'html'
                        ], 
                      'created_at',
                    ],
                ]); ?>
                <?php Pjax::end(); ?>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
      <div class="card">
          <div class="card-header card-header-danger card-header-icon">
            <!-- <div class="card-icon">
              <i class="material-icons">notifications</i>
            </div> -->
            <h4 class="card-title">
                Notifications
            </h4>
          </div>
          <div class="card-body">
            <?php foreach($notifications as $notification): ?>
              <b><?= $notification->subject ?></b><br>
              <?= $notification->message ?><br>
              <?= $notification->created_at ?><br><br>
            <?php endforeach; ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>